[package]
org = "ballerina"
name = "socket"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[platform.java11.dependency]]
path = "../socket-native/build/libs/socket-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "socket"
version = "@project.version@"

[[platform.java11.dependency]]
path = "../socket-test-utils/build/libs/socket-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.socket"
scope = "testOnly"
artifactId = "socket"
version = "@project.version@"
