[project]
org-name = "ballerina"
version = "0.6.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "socket"
    version = "1.3.0-SNAPSHOT"
    path = "../socket-native/build/libs/socket-native-1.3.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["socket"]

    [[platform.libraries]]
    artifactId = "socket"
    version = "1.3.0-SNAPSHOT"
    path = "../socket-test-utils/build/libs/socket-test-utils-1.3.0-SNAPSHOT.jar"
    groupId = "org.ballerinalang.stdlib.socket"
    modules = ["socket"]
